name: netlifydeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write       
  deployments: write    
  statuses: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: dependencies
        run: npm install

      - name: build
        run: |
          npm run build --configuration=production
          sleep 10

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          # enable-pull-request-comment: false
          # enable-commit-comment: true
          # overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITEID }}
        timeout-minutes: 1