name: netlifydeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write       
  deployments: write    
  statuses: write  

jobs:
  netlifydeployment:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: dependencies & build
        run: |
          npm install
          npm run build --configuration=production
          sleep 2
          # echo "/*    /index.html   200" > dist/srihari-portfolio/_redirects


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist/srihari-portfolio'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_PAT }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITEID }}
        timeout-minutes: 1