name: netlifydeployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo
        uses: actions/checkout@v4

      - name: nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      - name: dependencies
        run: npm install

      - name: build
        run: |
          npm run build --configuration=production
          pwd
          ll